### ISSUE TITLE
Issue with Quest

### ISSUE THREAD

**Issue by NoltoxGit** [Krakenied/BlockTracker#2]
Hello,
I have a quest that requires breaking mangrove logs.
But when a player places a "mangrove propagule" to grow water, it says that the action doesn't count because "**BlockTracker**" considers that the block was placed by a player, so the quest isn't completed.

My quest:
```yml
tasks:
  nether6:
    type: "blockbreak"
    amount: 24
    block: "MANGROVE_LOG"
    reverse-if-placed: true
    allow-negative-progress: false
    allow-silk-touch: true
    check-playerblocktracker: true
````

There a video for illustrate the bug:

https://github.com/user-attachments/assets/798583ae-38b4-49da-bdb3-c1c19df80048
